### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by bcade** [TianrunCai/EXTEND#1]
Hello Austin,

There appear to be hard-coded, missing dependencies in EXTEND:

python example_script.py 
Traceback (most recent call last):
  File "example_script.py", line 2, in <module>
    from extend import cleanreport,report_processor
  File "C:\Users\AustinMain\AppData\Local\Enthought\Canopy\User\lib\site-packages\personal_package\numExtrator\report_processor.py", line 1, in <module>
ImportError: No module named personal_package.numExtrator

Does numExtrator exist in a public repository, and can it be integrated given the binary package code?

Thank you,
Brian Cade

**Comment by TianrunCai** [comment]
Thanks for making the comment. I have made a Windows EXE version with interface.
